lib/tanks_web/router.ex
defmodule TanksWeb.Router do
  use TanksWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session # provides put_session\3, get_session\2
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TanksWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", TanksWeb do
    pipe_through :browser

    get "/", AuthController, :index
    get "/register", AuthController, :register
    post "/", AuthController, :login
    delete "/", AuthController, :logout
  end

  scope "/", TanksWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, except: [:index, :new]
    get "/room/:name", RoomController, :show
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TanksWeb do
    pipe_through :api
    get "/room_status/:name", PageController, :get_room_status
  end
end

lib/tanks_web/views/layout_view.ex
defmodule TanksWeb.LayoutView do
  use TanksWeb, :view
end

lib/tanks_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Tanks!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div id="masthead">
      <nav>
        <ul class="nav nav-pills">
          <%= if @current_user do %>
            <script type="text/javascript">
              window.user = <%= @current_user.id %>;
            </script>
            <li>
              Logged in as: <%= link raw(@current_user.name), to: user_path(@conn, :show, @current_user.id), class: "btn btn-info" %>
            </li>
            <li>
              <%= link "Logout", to: auth_path(@conn, :logout), method: :delete, class: "btn btn-light" %>
            </li>
          <% else %>
            <li>
              <%= link "Sign in", to: auth_path(@conn, :index), class: "btn btn-light" %>
            </li>
          <% end %>
        </ul>
      </nav>
      <%= if @view_module == TanksWeb.PageView do %>
        <div id="banner-image"></div>
      <% end %>
      <h3>Welcome to Tank Game! A 2~4 players Game!</h3>
    </div>
    <div class="container">


      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info text-center" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>

      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger text-center" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>