lib/tanks_web/router.ex
defmodule TanksWeb.Router do
  use TanksWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session # provides put_session\3, get_session\2
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TanksWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", TanksWeb do
    pipe_through :browser

    get "/", AuthController, :index
    get "/register", AuthController, :register
    post "/", AuthController, :login
    delete "/", AuthController, :logout
  end

  scope "/", TanksWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, except: [:index, :new]
    get "/room/:name", RoomController, :show
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TanksWeb do
    pipe_through :api
    get "/room_status/:name", PageController, :get_room_status
  end
end

lib/tanks_web/templates/page/index.html.eex
<div class="row">
  <div class="col text-center">
    <!-- The input field to create room -->
    <script type="text/javascript">
      window.api_game_url = "<%= page_path(@conn, :get_room_status, "placeholder") %>";
      window.room_url = "<%= room_path(@conn, :show, "placeholder") %>";
    </script>
    <div class="container">
      <div class="row">

        <div class="col-lg-9">
          <div class="section section-create-room">
            <div id="create-room-field"></div>
          </div>
          <div class="divider"><span>OR</span></div>


          <div class="section section-join-others">
            <h2>Join Others</h2>
            <div id="rooms-list"></div>
          </div>
        </div>

        <div class="col-lg-3">
          <div id="lobby-chat" style="display:flex; min-height:550px;" class="mt-4"></div>
        </div>
      </div>
    </div>
  </div>
</div>